angular.module('login_app')
  .config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('es', {
      'PWSS': 'Tu Contraseña no es la correcta, verifica e intenta nuevamente.',
      'EMSS': 'Tu Correo electronico no esta asignado a ninguna cuenta!',
      'ERSS': 'Tu Correo electronico ya esta asignado a una cuenta!',
      'PHE': 'Correo Electronico',
      'PHP': 'Contraseña',
      'BSS': 'Inicia Sesion',
      'CASS': 'No tienes cuenta con nosotros?',
      'CASC': 'Ya tienes cuenta con nosotros?',
      'RRAS': 'Registrate aqui!',
      'BSLS': 'cambia de idioma',
      'ALLU': 'Todos los usuarios',
      'INDX': 'Indice',
      'USRN': 'Nombre de usuario',
      'EMTA': 'Correo electronico',
      'ETTA': 'Editar',
      'DELE': 'Borrar',
      'EDIT': 'Editar',
      'EDEL': 'Borrar',
      'EDSR': 'Edita este usuario',
      'URSE': 'Nombre de usuario',
      'UREM': 'Correo electronico',
      'SAVE': 'Guardar',
      'CLOS': 'Cerrar',
      'DEUS': 'Vas a eliminar el usuario y toda su informacion, no se podra deshacer',
      'AYSR': 'Estas seguro?',
      'YESS': 'Si',
      'NOTT': 'No'
    });

    $translateProvider.translations('en', {
      'PWSS': ' Your Password is not correct, verify and try again.',
      'EMSS': 'Your email is not assigned to any account!',
      'ERSS': 'Your Email is already assigned to an account!',
      'PHE': 'Email',
      'PHP': 'Password',
      'BSS': 'Sign in',
      'CASS': 'Dont have an account with us?',
      'CASC': 'You already have an account with us?',
      'RRAS': 'Sign up',
      'BSLS': 'Changing the language ',
      'ALLU': 'All users',
      'INDX': 'Index',
      'USRN': 'Username',
      'EMTA': 'Email',
      'ETTA': 'Edit',
      'DELE': 'Delete',
      'EDIT': 'Edit',
      'EDEL': 'Delete',
      'EDSR': 'Edit the user',
      'URSE': 'Username',
      'UREM': 'Email',
      'SAVE': 'Save',
      'CLOS': 'Close',
      'DEUS': 'You re going to delete the user and all their information, it cant be undone',
      'AYSR': 'Are you sure',
      'YESS': 'Yes',
      'NOTT': 'Not',
    });

    $translateProvider.preferredLanguage('es');
  }])